print('Hello World!', sep=' ---> ')
print('Hello World!', 'Hello World!', 'Hello World!', 456, 5.4, sep=' ---> ')
print('Hello World!', sep=' ---> ')
print('Hello World!', sep=' ---> ')
print('Площадь квадрата', 564, sep=': ')
